#!/usr/bin/env node
/*
 * style-guard: mechanical enforcement of the org Web Design Style guide.
 *
 * Three checks:
 *   1. src/styles/utilities.css and src/styles/modal.css are verbatim copies
 *      from the skill and have not been hand-edited (SHA-256 comparison).
 *   2. No src/** source file smuggles in inline styles, Tailwind, Bootstrap or
 *      !important.
 *   3. No src/**\/*.css other than tokens.css carries a raw hex color, px
 *      length or rem literal -- every value must come from a token.
 *
 * Run `node scripts/style-guard.mjs --update` after a deliberate, reviewed
 * refresh of the copied files to re-record their hashes below.
 */

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SRC = join(ROOT, 'src');
const SELF = join(HERE, 'style-guard.mjs');

/* BEGIN VERBATIM HASHES (regenerate with --update) */
const VERBATIM = {
  'src/styles/utilities.css':
    'd4a294e33e84f1c1f9d3f52030bff268a20847fda09f61660854bd566d50ee3e',
  'src/styles/modal.css':
    '55e18bb1399f4b46ed125b895ee653506961d69d1d330d35ab85d87c1d678545',
};
/* END VERBATIM HASHES */

/** Files exempt from the token/`!important` scans: they are verbatim copies. */
const COPIED = new Set(Object.keys(VERBATIM));
/** The one file allowed to contain raw design values. */
const TOKENS_FILE = 'src/styles/tokens.css';

const SOURCE_BANS = [
  { pattern: /style=\{\{/, message: 'inline style attribute (use utility classes or a BEM block)' },
  // Match the frameworks where they would actually be pulled in (an import, a
  // stylesheet reference, a CDN URL) rather than anywhere the words appear:
  // "bootstrap config" is a legitimate phrase for the startup handshake.
  {
    pattern:
      /(?:from\s*['"]|require\(\s*['"]|@import\s*['"]|url\(\s*['"]?|href=['"]|src=['"])[^'")]*\b(bootstrap|tailwind)/i,
    message: 'Bootstrap/Tailwind import (this project uses utilities.css + BEM only)',
  },
  {
    pattern: /(@tailwind\b|tailwind\.config|bootstrap-icons|bootstrap(\.min)?\.(css|js)\b)/i,
    message: 'Bootstrap/Tailwind asset reference (this project uses utilities.css + BEM only)',
  },
  { pattern: /!important/, message: '!important (raise specificity with a BEM block instead)' },
];

const CSS_BANS = [
  { pattern: /#[0-9a-fA-F]{3,8}\b/, message: 'raw hex color (define an RGB-triplet token in tokens.css)' },
  {
    pattern: /(?<![\w-])\d+(\.\d+)?px\b/,
    message: 'raw px length (use a --space-* / --radius-* token)',
    skipInMedia: true,
  },
  {
    pattern: /(?<![\w-])\d+(\.\d+)?rem\b/,
    message: 'raw rem length (use a --space-* / --font-size-* token)',
    skipInMedia: true,
  },
];

function walk(dir, exts, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, exts, out);
    } else if (exts.some((e) => entry.endsWith(e))) {
      out.push(full);
    }
  }
  return out;
}

function sha256(path) {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function report(failures, rel, line, lineNo, message) {
  failures.push(`${rel}:${lineNo}: ${message}\n    ${line.trim()}`);
}

function main() {
  const update = process.argv.includes('--update');

  if (update) {
    const next = {};
    for (const rel of Object.keys(VERBATIM)) next[rel] = sha256(join(ROOT, rel));
    const body = Object.entries(next)
      .map(([k, v]) => `  '${k}':\n    '${v}',`)
      .join('\n');
    const self = readFileSync(SELF, 'utf8').replace(
      /\/\* BEGIN VERBATIM HASHES[\s\S]*?\/\* END VERBATIM HASHES \*\//,
      `/* BEGIN VERBATIM HASHES (regenerate with --update) */\nconst VERBATIM = {\n${body}\n};\n/* END VERBATIM HASHES */`,
    );
    writeFileSync(SELF, self);
    console.log('style-guard: recorded hashes for', Object.keys(next).join(', '));
    return;
  }

  const failures = [];

  for (const [rel, expected] of Object.entries(VERBATIM)) {
    const actual = sha256(join(ROOT, rel));
    if (actual !== expected) {
      failures.push(
        `${rel}: file differs from the verbatim copy in the org Web Design Style skill.\n` +
          `    expected sha256 ${expected}\n` +
          `    actual   sha256 ${actual}\n` +
          '    Do not edit this file. Put project rules in src/styles/components.css.\n' +
          '    If the skill itself changed, re-copy it and run: npm run style-guard -- --update',
      );
    }
  }

  for (const file of walk(SRC, ['.ts', '.tsx', '.css'])) {
    const rel = relative(ROOT, file);
    if (COPIED.has(rel)) continue;
    const isCss = rel.endsWith('.css');
    const bans = isCss && rel !== TOKENS_FILE ? [...SOURCE_BANS, ...CSS_BANS] : SOURCE_BANS;
    readFileSync(file, 'utf8')
      .split('\n')
      .forEach((line, i) => {
        // Media-query breakpoints are the one legitimate raw length in CSS:
        // custom properties are not allowed in a media prelude.
        const isMediaPrelude = /^\s*@media\b/.test(line);
        for (const { pattern, message, skipInMedia } of bans) {
          if (isMediaPrelude && skipInMedia) continue;
          if (pattern.test(line)) report(failures, rel, line, i + 1, message);
        }
      });
  }

  if (failures.length) {
    console.error('style-guard: FAILED\n');
    for (const f of failures) console.error('  ' + f + '\n');
    process.exit(1);
  }
  console.log('style-guard: OK');
}

main();
