"""Initial schema

Baseline for the refgenie1 schema, autogenerated from ``SQLModel.metadata``.
There is no upgrade path from pre-baseline revisions -- databases predating
this one are rebuilt, not migrated.

Revision ID: 1a0e5c7b9d21
Revises:
Create Date: 2026-07-22 07:25:47.776904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1a0e5c7b9d21"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assetclass",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("serving_modes", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="unique_name_and_version"),
    )
    op.create_table(
        "configuration",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("servers", sa.JSON(), nullable=True),
        sa.Column("genome_folder", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genome_stage_folder", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "genome",
        sa.Column("digest", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("species_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("common_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("taxon_id", sa.Integer(), nullable=True),
        sa.Column("assembly_source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("assembly_accession", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("assembly_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("remote_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(op.f("ix_genome_species_name"), "genome", ["species_name"], unique=False)
    op.create_index(op.f("ix_genome_taxon_id"), "genome", ["taxon_id"], unique=False)
    op.create_index(
        op.f("ix_genome_assembly_source"), "genome", ["assembly_source"], unique=False
    )
    op.create_index(
        op.f("ix_genome_assembly_accession"), "genome", ["assembly_accession"], unique=False
    )
    op.create_table(
        "alias",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("genome_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["genome_digest"],
            ["genome.digest"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "assetclasslink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["assetclass.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["assetclass.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetclassseekkey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("file", "directory", "prefix", "string", "json", name="seekkeytype"),
            nullable=False,
        ),
        sa.Column("asset_class_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_class_id"],
            ["assetclass.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetgroup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("asset_class_id", sa.Integer(), nullable=False),
        sa.Column("genome_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_class_id"],
            ["assetclass.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genome_digest"],
            ["genome.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("genome_digest", "name", name="unique_genome_group_name"),
    )
    op.create_index(
        op.f("ix_assetgroup_genome_digest"), "assetgroup", ["genome_digest"], unique=False
    )
    op.create_table(
        "datachannel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type", sa.Enum("ftp", "http", "https", "local", name="datachanneltype"), nullable=False
        ),
        sa.Column("index_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("encrypted_credentials", sa.JSON(), nullable=True),
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configuration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output_asset_class_id", sa.Integer(), nullable=False),
        sa.Column("command_templates", sa.JSON(), nullable=False),
        sa.Column("input_params", sa.JSON(), nullable=True),
        sa.Column("input_files", sa.JSON(), nullable=True),
        sa.Column("input_assets", sa.JSON(), nullable=True),
        sa.Column("docker_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("custom_seek_keys", sa.JSON(), nullable=True),
        sa.Column("default_asset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("inherent", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["output_asset_class_id"],
            ["assetclass.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version"),
    )
    op.create_index(
        op.f("ix_recipe_output_asset_class_id"), "recipe", ["output_asset_class_id"], unique=False
    )
    op.create_table(
        "remote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sa.Enum("s3", "http", "https", name="remotetype"), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("push_command", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("configuration_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["configuration_id"],
            ["configuration.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset",
        sa.Column("digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("serving_modes_override", sa.JSON(), nullable=True),
        sa.Column("colocate", sa.JSON(), nullable=True),
        sa.Column("asset_group_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_group_id"],
            ["assetgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("digest"),
        sa.UniqueConstraint("digest"),
    )
    op.create_index(op.f("ix_asset_asset_group_id"), "asset", ["asset_group_id"], unique=False)
    op.create_table(
        "recipeassetclassesinputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("asset_class_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("default", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_class_id"],
            ["assetclass.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipeassetclassesinputs_asset_class_id"),
        "recipeassetclassesinputs",
        ["asset_class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipeassetclassesinputs_recipe_id"),
        "recipeassetclassesinputs",
        ["recipe_id"],
        unique=False,
    )
    op.create_table(
        "assetlink",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("child_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_digest"],
            ["asset.digest"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_digest"],
            ["asset.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetname",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_group_id", sa.Integer(), nullable=False),
        sa.Column("asset_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("build_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("build_level1", sa.JSON(), nullable=True),
        sa.Column("build_digest_scheme", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("build_timestamp", sa.DateTime(), nullable=True),
        sa.Column("refgenie_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=True),
        sa.Column("docker_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("docker_image_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_digest"],
            ["asset.digest"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_group_id"],
            ["assetgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_group_id", "name", name="unique_group_asset_name"),
    )
    op.create_index(op.f("ix_assetname_asset_digest"), "assetname", ["asset_digest"], unique=False)
    op.create_index(op.f("ix_assetname_build_digest"), "assetname", ["build_digest"], unique=False)
    op.create_index(
        "unique_group_build_digest", "assetname", ["asset_group_id", "build_digest"], unique=False
    )
    op.create_index(
        op.f("ix_assetname_asset_group_id"), "assetname", ["asset_group_id"], unique=False
    )
    op.create_index(
        "unique_default_per_group",
        "assetname",
        ["asset_group_id"],
        unique=True,
        sqlite_where=sa.text("is_default"),
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "seekkey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("file", "directory", "prefix", "string", "json", name="seekkeytype"),
            nullable=False,
        ),
        sa.Column("asset_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_digest"],
            ["asset.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stagedasset",
        sa.Column("asset_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("directory_contents", sa.JSON(), nullable=True),
        sa.Column("build_commands", sa.JSON(), nullable=True),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("tarball_digest", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("tarball_size", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_digest"],
            ["asset.digest"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_digest", "mode", name="unique_asset_mode"),
    )
    op.create_index(
        op.f("ix_stagedasset_asset_digest"), "stagedasset", ["asset_digest"], unique=False
    )
    op.create_table(
        "remoteassetlink",
        sa.Column("remote_id", sa.Integer(), nullable=False),
        sa.Column("asset_digest", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mode", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pushed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_digest", "mode"],
            ["stagedasset.asset_digest", "stagedasset.mode"],
        ),
        sa.ForeignKeyConstraint(
            ["remote_id"],
            ["remote.id"],
        ),
        sa.PrimaryKeyConstraint("remote_id", "asset_digest", "mode"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("remoteassetlink")
    op.drop_index(op.f("ix_stagedasset_asset_digest"), table_name="stagedasset")
    op.drop_table("stagedasset")
    op.drop_table("seekkey")
    op.drop_index(
        "unique_default_per_group",
        table_name="assetname",
        sqlite_where=sa.text("is_default"),
        postgresql_where=sa.text("is_default"),
    )
    op.drop_index(op.f("ix_assetname_asset_group_id"), table_name="assetname")
    op.drop_index(op.f("ix_assetname_asset_digest"), table_name="assetname")
    op.drop_table("assetname")
    op.drop_table("assetlink")
    op.drop_index(
        op.f("ix_recipeassetclassesinputs_recipe_id"), table_name="recipeassetclassesinputs"
    )
    op.drop_index(
        op.f("ix_recipeassetclassesinputs_asset_class_id"), table_name="recipeassetclassesinputs"
    )
    op.drop_table("recipeassetclassesinputs")
    op.drop_index(op.f("ix_asset_asset_group_id"), table_name="asset")
    op.drop_table("asset")
    op.drop_table("remote")
    op.drop_index(op.f("ix_recipe_output_asset_class_id"), table_name="recipe")
    op.drop_table("recipe")
    op.drop_table("datachannel")
    op.drop_index(op.f("ix_assetgroup_genome_digest"), table_name="assetgroup")
    op.drop_table("assetgroup")
    op.drop_table("assetclassseekkey")
    op.drop_table("assetclasslink")
    op.drop_table("alias")
    op.drop_index(op.f("ix_genome_species_name"), table_name="genome")
    op.drop_table("genome")
    op.drop_table("configuration")
    op.drop_table("assetclass")
    # ### end Alembic commands ###
    # DROP TABLE leaves PostgreSQL ENUM types behind, so a later upgrade would
    # fail on "type already exists". No-op on SQLite, where enums are VARCHAR.
    bind = op.get_bind()
    for enum_name in ("seekkeytype", "datachanneltype", "remotetype"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
